name: Create an issue on this repo when repository_dispatch event used on repo.

on:
  repository_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - uses: ./.github/actions/update-issues-action
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USER: ${{ secrets.GH_USER }}
          GH_REPO: ${{ secrets.GH_REPO }}
          GH_ORG: ${{ secrets.GH_ORG }}
